sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk11

cache:
  directories:
    - '$HOME/.m2/repository'

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "target/AuthMe-5.6.0-SNAPSHOT.jar"
  on:
    tags: true
